<a href="https://colab.research.google.com/github/dlwltn98/tensorflow_study/blob/master/tensorflow1/Deep_Learning4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4. 신경망 완성 : 히든 레이어


* 보스턴 : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
* 아이리스 : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

**Boston**

In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(file_path)

독립 = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = boston[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 25.2420
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 25.0435
Epoch 3/10
16/16 [==============================] - 0s 940us/step - loss: 25.4973
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 25.2225
Epoch 5/10
16/16 [==============================] - 0s 896us/step - loss: 26.0248
Epoch 6/10
16/16 [==============================] - 0s 900us/step - loss: 24.4250
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 24.9075
Epoch 8/10
16/16 [==============================] - 0s 990us/step - loss: 25.3027
Epoch 9/10
16/16 [==============================] - 0s 983us/step - loss: 25.1129
Epoch 10/10
16/16 [==============================] - 0s 971us/step - loss: 25.8663


In [ ]:
# 멀티 레이어 학습에 대한 확인
# 오른쪽 Param = 가중치
# 13 + 항 1개 = 14 *10 = 140, 10 + 항 1개 = 11 * 1 = 11
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(독립[:5]))
print(종속[:5])

[[28.976143]
 [23.353222]
 [28.8124  ]
 [28.226242]
 [27.301033]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


**Iris**

In [ ]:
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_path)

iris = pd.get_dummies(iris)

독립 = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = iris[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0443 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0498 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0450 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0443 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0451 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0470 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0486 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0461 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0509 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0453 - accuracy: 0.9800


In [ ]:
print(model.predict(독립[0:5]))
print(종속[0:5])

[[1.00000000e+00 4.56228631e-12 5.94656235e-09]
 [1.00000000e+00 1.00444514e-10 4.56832971e-08]
 [1.00000000e+00 2.87389453e-11 2.23526371e-08]
 [9.99999881e-01 4.59633637e-10 1.31847912e-07]
 [1.00000000e+00 4.13207185e-12 5.78304116e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
