<a href="https://colab.research.google.com/github/dlwltn98/tensorflow_study/blob/master/tensorflow1/Deep_Learning3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3. 아이리스 품종 분류


*  아이리스 : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv


In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 1. 과거의 데이터를 준비
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# 원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
# 독립변수, 종속변수
독립 = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = encoding[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 2. 모델의 구조를 만든다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
# 3. 데이터 모델응 학습(FIT)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1372 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1372 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1375 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1375 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1370 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1367 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1366 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1368 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1368 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1364 - accuracy: 0.9800


In [ ]:
# 4.모델을 이용
model.predict(독립[0:5])
# setosa일 확률 96프로

array([[9.9951148e-01, 4.8855616e-04, 3.9229917e-09],
       [9.9775702e-01, 2.2429856e-03, 5.6377750e-08],
       [9.9899572e-01, 1.0042690e-03, 1.8758731e-08],
       [9.9725240e-01, 2.7475003e-03, 1.0842970e-07],
       [9.9961346e-01, 3.8657020e-04, 2.9859890e-09]], dtype=float32)

In [ ]:
print(종속[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
# 맨아래 자료 확인
model.predict(독립[-5:])

array([[2.1898222e-07, 1.3212565e-01, 8.6787421e-01],
       [4.4959970e-07, 1.6757573e-01, 8.3242381e-01],
       [1.0074494e-06, 2.2907740e-01, 7.7092165e-01],
       [1.8682529e-07, 9.1034070e-02, 9.0896571e-01],
       [2.1896494e-06, 2.3507981e-01, 7.6491803e-01]], dtype=float32)

In [ ]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
# 학습한 가중치
model.get_weights()
# 칼럼[0] - setosa ... + 함수 씌워야함

[array([[ 1.0078008 ,  0.50115657, -0.8519766 ],
        [ 3.177088  ,  0.32801193, -1.4129587 ],
        [-3.9386284 , -0.57560974,  1.6173965 ],
        [-4.5482593 , -0.95756185,  2.1737492 ]], dtype=float32),
 array([ 1.6630455,  1.1687642, -1.2656856], dtype=float32)]